[build]
publish = "dist"
command = "npm install && npm run build-client"

[context.deploy-preview.environment]
VUE_APP_SERVER_ADDRESS = "https://stark-plains-46658.herokuapp.com"

[context.branch-deploy.environment]
VUE_APP_SERVER_ADDRESS = "https://stark-plains-46658.herokuapp.com"
